[package]
name = "example"
version = "0.1.0"
authors = ["author's name <author's email>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
eosio = { path = "eosio-rust/crates/eosio" }
eosio_cdt = { path = "eosio-rust/crates/eosio_cdt" }


[profile.release]
lto = true
